const mongoose=require('mongoose');
const Schema=mongoose.Schema;


/*
    Comapny Name : Name of the Company
    Stock Exchange : Stock Exchange in which the stock is traded
    Ticker Symbol : Tiker symbol of the stock
    
    Valuation-
      Market Capitalization : Total dollar value of the company's outstanding shares of stock
      Enterprise Value (MRQ) : Market Capitalization + Total Debt - Cash and Cash Equivalents in Most Recent Quarter(MRQ)
      Enterprise Value/EBITDA (TTM) : Ratio of Enterprise Value/EBITDA in the Trailing Twelve Months(TTM)
      Total Shares Outstanding (MRQ) : Total number of shares currently held by all it's shareholders
      Number of Employees : Number of Employees in the Company
      Number of Shareholders : Number of Shareholders of the Company
      Price to Earnings Ratio (TTM) : PE Ratio of the Company in the Trailing Twelve Months(TTM)
      Price to Revenue Ratio (TTM) : PR Ratio of the Company in the Trailing Twelve Months(TTM)
      Price to Book (FY) : PB Ratio of the Company for the past Fiscal Year(FY)
      Price to Sales (FY) : PS Ratio of the Company for the past Fiscal Year(FY)
    
    Price History-
      Average Volume (10 day) : (Total Amount Traded in the past 10 days)/10
      1-Year Beta : Beta Ratio for the past 1 Year Period
      52 Week High : Highest price of the Stock in the past 52 weeks
      52 Week Low : Lowest price of the Stock in the past 52 weeks

    Balance Sheet-
      Quick Ratio (MRQ) : (Current Assets-Inventory)/Current Liabilities in Most Recent Quarter(MRQ)
      Current Ratio (MRQ) : Current Assets/Current Liabilities in Most Recent Quarter(MRQ)
      Debt to Equity Ratio (MRQ) : Total Liabilities/Total Shareholders' Equity in Most Recent Quarter(MRQ)
      Net Debt (MRQ) : Short-Term Debt + Long-Term Debt - Cash and Cash Equivalents in Most Recent Quarter(MRQ)
      Total Debt (MRQ) : Short-Term Debt + Long-Term Debt in Most Recent Quarter(MRQ)
      Total Assets (MRQ) : Total Assets owned by the Company as stated in Most Recent Quarter(MRQ)

    Dividends-
      Dividends Paid (FY) : Total Dividends Paid in the past Fiscal Year(FY) 
      Dividends Yield (FY) : Annual Dividends per share/Current share price in the past Fiscal Year(FY)
      Dividends per Share (FY) : Dividends paid per share in the past Fiscal Year(FY)

    Operating Metrics-
      Return on Assets (TTM) : Net Income/Total Assets in the Trailing Twelve Months(TTM)
      Return on Equity (TTM) : Net Income/Shareholders' Equity in the Trailing Twelve Months(TTM)
      Return on Invested Capital (TTM) : ROIC of the Company in the Trailing Twelve Months(TTM)
      Revenue per Employee (TTM) : Average Revenue generated by each Employee towards the Company in the Trailing Twelve Months(TTM)

    Margins-
      Net Margin (TTM) : (Revenue-Cost)/Revenue in the Trailing Twelve Months(TTM)
      Gross Margin (TTM) : (Revenue-Cost of Goods Sold)/Revenue in the Trailing Twelve Months(TTM)
      Operating Margin (TTM) : Operating Income/Revenue in the Trailing Twelve Months(TTM)
      Pretax Margin (TTM) : Earnings before Tax/Sales in the Trailing Twelve Months(TTM)
    
    Income Statement-
      Basic EPS (FY) : Basic Earnings Per Share in the past Fiscal Year(FY)
      Basic EPS (TTM) : Basic Earnings Per Share in the Trailing Twelve Months(TTM)
      EPS Diluted (FY) : Diluted Earnings Per Share in the past Fiscal Year(FY)
      Net Income (FY) : Sales - Cost of Goods Sold - Expenses in the past Fiscal Year(FY)
      EBITDA (TTM) : Earnings Before Interest, Taxes, Depreciation, and Amortization (EBITDA) in the Trailing Twelve Months (TTM)
      Gross Profit (MRQ) : Revenue - Cost of Goods Sold in Most Recent Quarter(MRQ)
      Gross Profit (FY) : Revenue - Cost of Goods Sold in the past Fiscal Year(FY)
      Last Year Revenue (FY) : Revenue earned in the past Fiscal Year(FY)
      Total Revenue (FY) : Total Revenue earned in the past Fiscal Year(FY)
      Free Cash Flow (TTM) : Net Operaing Profit after Taxes - Investments in the Trailing Twelve Months(TTM)

*/


let StockSchema=Schema({
    _id: {type: String, unique: true},
    "Company Name": {type: String, required: true, default: "-"},
    "Valuation": {
      "Market Capitalization": {type: Number, required: true, default: null},
      "Enterprise Value (MRQ)": {type: Number, required: true, default: null},
      "Enterprise Value/EBITDA (TTM)": {type: Number, required: true, default: null},
      "Total Shares Outstanding (MRQ)": {type: Number, required: true, default: null},
      "Number of Employees": {type: Number, required: true, default: null},
      "Number of Shareholders": {type: Number, required: true, default: null},
      "Price to Earnings Ratio (TTM)": {type: Number, required: true, default: null},
      "Price to Revenue Ratio (TTM)": {type: Number, required: true, default: null},
      "Price to Book (FY)": {type: Number, required: true, default: null},
      "Price to Sales (FY)": {type: Number, required: true, default: null},
    },
    "Price History": {
      "Average Volume (10 day)": {type: Number, required: true, default: null},
      "1-Year Beta": {type: Number, required: true, default: null},
      "52 Week High": {type: Number, required: true, default: null},
      "52 Week Low": {type: Number, required: true, default: null},
    },
    "Balance Sheet": {
      "Quick Ratio (MRQ)": {type: Number, required: true, default: null},
      "Current Ratio (MRQ)": {type: Number, required: true, default: null},
      "Debt to Equity Ratio (MRQ)": {type: Number, required: true, default: null},
      "Net Debt (MRQ)": {type: Number, required: true, default: null},
      "Total Debt (MRQ)": {type: Number, required: true, default: null},
      "Total Assets (MRQ)": {type: Number, required: true, default: null},
    },
    "Dividends": {
      "Dividends Paid (FY)": {type: Number, required: true, default: null},
      "Dividends Yield (FY)": {type: Number, required: true, default: null},
      "Dividends per Share (FY)": {type: Number, required: true, default: null},
    },
    "Operating Metrics": {
      "Return on Assets (TTM)": {type: Number, required: true, default: null},
      "Return on Equity (TTM)": {type: Number, required: true, default: null},
      "Return on Invested Capital (TTM)": {type: Number, required: true, default: null},
      "Revenue per Employee (TTM)": {type: Number, required: true, default: null},
    },
    "Margins": {
      "Net Margin (TTM)": {type: Number, required: true, default: null},
      "Gross Margin (TTM)": {type: Number, required: true, default: null},
      "Operating Margin (TTM)": {type: Number, required: true, default: null},
      "Pretax Margin (TTM)": {type: Number, required: true, default: null},
    },
    "Income Statement": {
      "Basic EPS (FY)": {type: Number, required: true, default: null},
      "Basic EPS (TTM)": {type: Number, required: true, default: null},
      "EPS Diluted (FY)": {type: Number, required: true, default: null},
      "Net Income (FY)": {type: Number, required: true, default: null},
      "EBITDA (TTM)": {type: Number, required: true, default: null},
      "Gross Profit (MRQ)": {type: Number, required: true, default: null},
      "Gross Profit (FY)": {type: Number, required: true, default: null},
      "Last Year Revenue (FY)": {type: Number, required: true, default: null},
      "Total Revenue (FY)": {type: Number, required: true, default: null},
      "Free Cash Flow (TTM)": {type: Number, required: true, default: null},
    },
    "Stock Exchange": {type: String, required: true, default: "-"},
    "Ticker Symbol": {type: String, required: true, default: "-"},
    addToWishlist : {type:Boolean, required:true, default: false},
    _v: {type:Number, select: false},
});


module.exports=mongoose.model('Stock', StockSchema);